"""Server-owned public task identity primitives.

A task ID is an immutable UUID generated by DopaMatrix for one submitted task.
It is public task provenance, never a client-supplied session, idempotency key,
Reservation owner-attempt ID, or child execution ID.
"""

from __future__ import annotations

import uuid


CLIENT_TASK_ID_NOT_ALLOWED = "CLIENT_TASK_ID_NOT_ALLOWED"
PUBLIC_TASK_ID_GENERATION_COLLISION = "PUBLIC_TASK_ID_GENERATION_COLLISION"
VIDEO_TASK_TASK_ID_SCHEMA_RESET_REQUIRED = (
    "VIDEO_TASK_TASK_ID_SCHEMA_RESET_REQUIRED"
)


def new_task_id() -> str:
    """Return the canonical server-owned ID for one authoritative task."""
    return str(uuid.uuid4())
